- name: deploy-toolbox | all
  hosts: all
  remote_user: root
  become: true
  tasks:
  - name: Install GNUPG
    ansible.builtin.package:
      name: gnupg2
      state: present

  - name: Install ansible
    ansible.builtin.include_role:
      name: ansible
    tags: ansible

  - name: Install git
    ansible.builtin.include_role:
      name: git
    tags: git